name: KommatiParaClients application build
on: [push]
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyspark
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install wheel setuptools check-wheel-contents
    - name: Test with pytest
      run: |
        pytest
    - name: Create distribution file
      run: |
        python3 setup.py bdist_wheel
    - name: Check distribution file
      run: |
        check-wheel-contents ./dist/KommatiParaClients*
    - name: Download artifact from build job
      #uses: actions/download-artifact@v3
      uses: actions/upload-artifact@v3
      with:
        name: KommatiParaClients
        path: ./dist/KommatiParaClients*
